export const GET_STOCK_DATA = 'GET_STOCK_DATA';

export const ADD_STOCK = 'ADD_STOCK';
export const ADD_STOCK_FAILURE = 'ADD_STOCK_FAILURE'
export const NEW_STOCK_RECIEVED = 'NEW_STOCK_RECIEVED';

export const HYDRATE_STOCKS_REQUEST = 'HYDRATE_STOCKS_REQUEST';
export const HYDRATE_STOCKS_SUCCESS = 'HYDRATE_STOCKS_SUCCESS';
export const HYDRATE_STOCKS_FAILURE = 'HYDRATE_STOCKS_FAILURE';

export const DISCONNECT = 'disconnect';