export const GET_STOCK_DATA = 'GET_STOCK_DATA';

export const ADD_STOCK = 'ADD_STOCK';
export const ADD_STOCK_FAILURE = 'ADD_STOCK_FAILURE'
export const NEW_STOCK_RECIEVED = 'NEW_STOCK_RECIEVED';

export const HYDRATE_STOCKS_REQUEST = 'HYDRATE_STOCKS_REQUEST';
export const HYDRATE_STOCKS_SUCCESS = 'HYDRATE_STOCKS_SUCCESS';
export const HYDRATE_STOCKS_FAILURE = 'HYDRATE_STOCKS_FAILURE';

export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const STOCK_DELETED = 'STOCK_DELETED';
export const DELETE_STOCK_FAILURE = 'DELETE_STOCK_FAILURE';

export const UPDATE_CHART_WIDTH = 'UPDATE_WIDTH';
export const UPDATE_CHART_HEIGHT = 'UPDATE_CHART_HEIGHT';
export const UPDATE_CHART_DIMENSIONS = 'UPDATE_CHART_DIMENSIONS';
export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';

//Disconnect is in lower case to correspond to socket.io data
export const DISCONNECT = 'disconnect';